metacats/blog/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = 'blog'


urlpatterns = [
    path('', blog_all, name='blog'),
    path('<int:pk>', blog_single, name='blog_single'),


]

metacats/maincat/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = 'maincat'

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),

]

metacats/metacats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maincat.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('merch/', include('merch.urls', namespace='merch')),
    path('collection/', include('collection.urls', namespace='collection')),
    path('', include('users.urls', namespace='users')),



]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metacats/users/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = 'users'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('logout/', logoutuser, name='logout'),

]

metacats/maincat/models.py
from django.db import models


class Cat(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/')
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.title

metacats/maincat/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, HttpResponseNotFound
from django.shortcuts import render
from .models import *

menu = [{'title': "merch", 'url_name': 'merch:merch'},
        {'title': "collection", 'url_name': 'collection:collection'},
        {'title': "blog", 'url_name': 'blog:blog'},
]


def index(request):
    return render(request, 'maincat/index.html', {'title': 'Metacats', 'menu': menu, })


def about(request):
    return render(request, 'maincat/about.html', {'title': 'About', 'menu': menu, })

metacats/maincat/templates/maincat/about.html
{% extends 'maincat/base.html' %}



{% block content %}

<div class="intro">
	<div class="container">
		<div class="intro__inner">

			<h1 class="intro__title">about</h1>

			<p class="intro__text">
				Hello, dear friend. You're welcome in metacats world and our little community.

			<p class="intro__text">Metacats NFT project was released in the beginning of
			2024 year, and it was a long way of hard work to prepare everything.</p>

			<p class="intro__text">Metacats NFTs are a 10,000 piece collection of digital
			creatures, created by artist. If you like cg art and cats - you found your
			place in metaworld. Let's see where our path takes us...</p>

		</div>
	</div>
</div>

{% endblock content%}

metacats/maincat/templates/maincat/base.html
{% load static %}
{% load merch_tags %}


<html lang="en">

<head>
											<!--Links-->
	<script src="https://kit.fontawesome.com/5ca3c66f3f.js" crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'maincat/css/my_css1.css' %}"  />
	<link type="text/css" href="{% static 'maincat/css/styles_metacats.css' %}" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700&display=swap" rel="stylesheet">


	<title> {{ title }} </title>
</head>

											<!--Block MENU-->
{% block mainmenu %}
<header class="header">
	<div class="container3">
		<div class="header__inner">
			<a class="header__logo" href="{% url 'home:home' %}">Metacats</a>
			<nav class="nav" style="align-items: center;">
			{% for m in menu %}
				<a class="nav__link" href="{% url m.url_name %}">{{ m.title }}</a>
			{% endfor %}
				{% if request.user.is_authenticated %}
					<a class="nav__link" href="{% url 'users:signin' %}"><img src="{% static 'maincat/images/login_icon3.png'  %}"
																			  width="32" height="32" style="margin-left: 0px; margin-right: 0px;" alt=".."></a>
					<a class="nav-link" style="display: flex; align-items: center; margin-left: -40px; text-decoration: none; color: black;" >{{ user.username }}</a>
					<form action="{% url 'users:logout' %}" method="post" style="margin: 0 auto; display: block;">
            		{% csrf_token %}
            		<button class="btn1" type="submit" style="margin: 10px;">Log Out</button>
            		</form>
					{% else %}
					<a class="nav__link" href="{% url 'users:signin' %}"><img src="{% static 'maincat/images/login_icon2.png'  %}"
														   width="32" height="32" style="margin-left: 0px; margin-right: 0px;" alt="..">
					<span>LOGIN</span></a>
				{% endif %}
			</nav>
		</div>
	</div>
</header>
{% endblock mainmenu %}


<body>
											<!--Block CONTENT-->
{% block content %}
{% endblock content %}
										  <!--Block SOCIAL LINKS-->
{% block sociallinks %}
<div class="container_social">
	<div class="social__text" style="padding-left: 100px;">Follow our socials:</div>
	<div class="social" style="padding-left: 50px;">
		<a class="social_item" href="https://twitter.com/Mooncake66" target="_blank">
			<i class="fa-brands fa-square-x-twitter" style="color: #DCADEF;"></i></a>
		<a class="social_item" href="#" target="_blank">
			<i class="fa-brands fa-square-instagram" style="color: #DCADEF;"></i></a>
		<a class="social_item" href="#" target="_blank">
			<i class="fa-brands fa-discord" style="color: #DCADEF;"></i></a>
		<a class="social_item" href="#" target="_blank">
			<i class="fa-brands fa-telegram"  style="color: #DCADEF;"></i></a>
	</div >

	<div class="copyright">
		© 2024 Metacats. All rights reserved.
	</div>
</div>
{% endblock sociallinks %}

</body>
</html>

metacats/maincat/templates/maincat/index.html
{% extends 'maincat/base.html' %}

<body>
{% block content %}

<div class="intro">
	<div class="container">
		<div class="intro__inner">
			<h1 class="intro__title">About</h1>
			<p class="intro__text"> Hello, dear friend. You're welcome in metacats world and our little community </p>

			<a class="btn" href="../about">Learn more</a>
		</div>
	</div>
</div>

{% endblock content %}
</body>