metacats/blog/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = 'blog'


urlpatterns = [
    path('', blog_all, name='blog'),
    path('<int:pk>', blog_single, name='blog_single'),


]

metacats/merch/urls.py
from django.urls import path, include
from merch import views

app_name = 'merch'

urlpatterns = [
    path('', views.catalog, name='merch'),
    path('product/<slug:product_slug>/', views.product, name='product'),

]

metacats/metacats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maincat.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('merch/', include('merch.urls', namespace='merch')),
    path('collection/', include('collection.urls', namespace='collection')),
    path('', include('users.urls', namespace='users')),



]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metacats/merch/models.py
from django.db import models


# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Name')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    def __str__(self):
        return self.name


    class Meta:
        db_table = 'category'
        verbose_name_plural = 'categories'


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Name')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Description')
    image = models.ImageField(upload_to='merch_images', blank=True, null=True)
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2)
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(to=Categories, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Products'

    def display_id(self):
        return f'{self.id:05}'

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount/100, 2)
        return self.price

metacats/merch/views.py
from django.shortcuts import render
from maincat.views import menu
from merch.models import *


def catalog(request):
    goods = Products.objects.all()
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)

    if on_sale:
        goods = goods.filter(discount__gt=0)

    if order_by and order_by != 'default':
        goods = goods.order_by(order_by)

    return render(request, 'merch/catalog.html', {'menu': menu, 'goods': goods, })


def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)

    context = {
        'product': product,
        'menu': menu
    }

    return render(request, 'merch/product.html', context=context)

metacats/merch/templates/merch/catalog.html
{% extends 'maincat/base.html' %}
{% load static %}
{% load merch_tags %}


{% block content %}
                                            <!--Sort-->
<form method="get" action="" style="margin-top:140px; margin-left: 160px; position:relative; font-size: 15px;">
    <a style="margin-left: 10px;"> Sort By:</a>
        <select name="order_by" class="form-select" aria-label="Default select example" style="max-width: 400px; margin-bottom: 10px;">
            <option value="default">Default</option>
            <option value="-price">Price: High-Low</option>
            <option value="price">Price: Low-High</option>
        </select>

        <div class="form-check" method="get">
            <input class="form-check-input" type="checkbox" value="on" id="flexCheckDefault" name="on_sale">
            <label class="form-check-label" for="flexCheckDefault" >
                Only on Sale offers %
            </label>
        </div>

        <button type="submit" class="btn btn-light"
                style="margin: 0 auto; border-color: #DCADEF; margin-bottom: 20px; margin-top: 10px;">Show selected</button>

</form>

                                        <!--Products-->
<div class="container4">
    <ul class="products" style="margin-right:20px;">
        {% tag_products as products %}
        {% for product in goods %}
        <li >
            <a href="{% url 'merch:product' product.slug %} " style="text-decoration: none; color: black;">
                <div class="card rounded custom-shadow" >
                    {% if product.image %}
                        <img src="{{ product.image.url }}" alt=".." class="card-img-top">
                    {% endif %}
                    <div class="card-body">
                            <p class="card-title">{{ product.name }}</p>
                        <p class="card-text text-truncate" style="padding: 1px;">{{ product.description }}</p>
                        <p class="product_id">id {{ product.display_id }}</p>
                        <div class="d-flex justify-content-between" style="font-size: 12px; font-weight: 200;">
                            {% if product.discount %}
                                <p><s>{{ product.price }}</s>$ | {{ product.sell_price }}$ </p>
                                <p><strong></strong></p>
                                <span class="badge bg-warning text-dark">-{{ product.discount }}% discount</span>
                            {% else %}
                                <p><strong>{{ product.price }} $</strong></p>
                            {% endif %}
                            <a class="nav__link" href="../login "><img src="{% static 'maincat/images/buy3.png' %}"
                            width="32" height="32" style="margin-left: 0px; margin-right: 0px;" alt="..">
                            <span>Buy now</span></a>
                        </div>
                    </div>
                </div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

metacats/merch/templates/merch/product.html
{% extends 'maincat/base.html' %}
{% load static %}
{% load merch_tags %}

{% block content %}

<div class="container4">
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">
                                            <!-- Miniature -->
                <div class="col-md-4">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" width="400" height="400" class="img-thumbnail"
                             data-bs-toggle="modal" data-bs-target="#imageModal1">
                    {% endif %}
                </div>

                <div class="col-md-4 ">
                    <p class="product_id mt-3">id = {{ product.display_id }}</p>
                </div>
                                        <!-- Enlarge image in modal window -->
                <div class="modal fade" id="imageModal1" tabindex="-1"
                     aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="close"></button>
                            </div>
                            <div class="modal-body">
                                 <img src="{{ product.image.url }}"
                                     class="img-fluid" alt="image {{ product.name }}">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                                         <!-- Product description -->
            <div class="card-body">
                <p class="card-text">Price: <strong>{{ product.sell_price }}$</strong></p>
                <p class="card-title"><strong>{{ product.name }}</strong></p>
                <p class="card-text">{{ product.description }}</p>
                <a class="nav__link" href="../login "><img src="{% static 'maincat/images/buy3.png'  %}"
                                                           width="32" height="32" style="margin-left: 150px; " alt="..">
                <span>Buy now</span></a>
            </div>

        </div>
    </div>
</div>
{% endblock content %}