metacats/blog/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = 'blog'


urlpatterns = [
    path('', blog_all, name='blog'),
    path('<int:pk>', blog_single, name='blog_single'),


]

metacats/metacats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maincat.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('merch/', include('merch.urls', namespace='merch')),
    path('collection/', include('collection.urls', namespace='collection')),
    path('', include('users.urls', namespace='users')),



]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metacats/users/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = 'users'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('logout/', logoutuser, name='logout'),

]

metacats/users/models.py
from django.db import models

# Create your models here.

metacats/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from blog.models import *


# class LoginUserForm(forms.Form):
#     username = forms.CharField(label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
#     password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class UsersignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UsersigninForm(forms.Form):
    username = forms.CharField(max_length=120)
    password = forms.CharField(max_length=30, widget=forms.PasswordInput())


class CommentForm(forms.Form):
    class Meta:
        model = CommentPost
        fields = ('text',)

metacats/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from maincat.views import menu
from .forms import *


def signup(request):

    if request.method == 'POST':
        form = UsersignupForm(request.POST)
        if form.is_valid():

            form.save()
            return HttpResponse('successfully signup')
    else:
        form = UsersignupForm()
    return render(request, 'users/signup.html', {'form': form, 'menu': menu,})


def signin(request):
    if request.method == 'POST':
        form = UsersigninForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('home:home'))
    else:
        form = UsersigninForm()
    return render(request, 'users/signin.html', {'form': form, 'menu': menu,})


def logoutuser(request):
    if request.method == 'POST':
        logout(request)
    return HttpResponseRedirect(reverse('home:home'))

metacats/users/templates/users/login.html
{% extends 'maincat/base.html' %}
{% load static %}


{% block content %}
<div class="container4">
    <h1 style="margin-top: 200 px;"> Authorization </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><button type="submit"> Enter </button></p>
        </form>
</div>
{% endblock content%}

metacats/users/templates/users/signin.html
{% extends 'maincat/base.html' %}
{% load static %}

{% block content %}
<div class="container4" style="padding-top: 100px; font-size: 14px;">
    <h1 style="margin-top: 200 px;"> SIGN IN </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><button type="submit"> Enter </button></p>
            <a class="nav__link" href="{% url 'users:signup' %}" style="color: #DCADEF;">Need to register?</a>
        </form>
</div>
{% endblock content%}

metacats/users/templates/users/signup.html
{% extends 'maincat/base.html' %}
{% load static %}

{% block content %}
<div class="container" style="font-size: 14px; line-height: 1.0;">
    <h1 style="padding-top: 150px; padding-bottom: 20px;"> SIGN UP </h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><button type="submit"> Enter </button></p>
            <a class="nav__link" href="{% url 'users:signin' %}" style="color: #DCADEF;">Already have account?</a>
        </form>
</div>
{% endblock content%}