metacats/blog/urls.py
from django.urls import path, include, re_path
from .views import *

app_name = 'blog'


urlpatterns = [
    path('', blog_all, name='blog'),
    path('<int:pk>', blog_single, name='blog_single'),


]

metacats/metacats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maincat.urls', namespace='home')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('merch/', include('merch.urls', namespace='merch')),
    path('collection/', include('collection.urls', namespace='collection')),
    path('', include('users.urls', namespace='users')),



]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

metacats/blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    title = models.CharField('Title', max_length=50)
    anons = models.CharField('Post', max_length=500)
    full_text = models.TextField('Article')
    date = models.DateTimeField('Date&Time')

    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'


class CommentPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT, verbose_name='article', blank=True, null=True,
                                related_name='comments_articles')
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='user', blank=True, null=True)
    text = models.TextField(verbose_name='Comment text')
    date = models.DateTimeField(auto_now=True, verbose_name='Date&Time of comment')
    moder = models.BooleanField(verbose_name='visibility', default=False)

metacats/blog/forms.py
from blog.models import CommentPost
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentPost
        fields = ('text',)

metacats/blog/views.py
from django.shortcuts import render, get_object_or_404
from requests import post

from users.forms import CommentForm
from .models import Post
from maincat.views import menu
from django.views.generic.edit import FormMixin
from .models import *
from .forms import CommentForm


def blog_all(request):
    post = Post.objects.all()
    return render(request, 'blog/blog_all.html', {'posts': post, 'menu': menu,})


def blog_single(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment = CommentPost.objects.filter(post=post)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comm = form.save(commit=False)
            comm.user = request.user
            comm.post = post
            comm.save()
        else:
            form = CommentForm()
    return render(request, 'blog/blog_single.html', {'post': post, 'menu': menu,
                                                     'form': form, 'comment': comment})

# def blog(request):
#     posts = Articles.objects.get(pk=1 )
#     form = CommentForm(request.POST)
#     if request.method == 'POST':
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comm = form.save(commit=False, Null=True)
#             comm.author = request.author
#             # comm.article_comment = posts
#             comm.save()
#         else:
#             form = CommentForm()
#     return render(request, 'blog/blog_single.html', {'posts': posts, 'menu': menu, 'form': form})
# class HomeDetailView(FormMixin):
#     form_class = CommentForm

metacats/blog/templates/blog/blog_all.html
{% extends 'maincat/base.html' %}
{% load static %}

<body>
{% block content %}

<div class="container4" style="margin: 100px; margin-top: 180px; " >
	<h1 class="intro__title" >Last updates:</h1>
{% for post in posts %}
		<section class="section--gray"  href="{% url 'blog:blog_single' post.id %}" style="background-color: white;
border-radius: 5px; font-size: 24px;">
		<div class="container__post" >
			<a href="{% url 'blog:blog_single' post.id %}">{{ post.title }}</a>
			<p>{{ post.anons }}</p>
			<p>{{ post.full_text }}</p>

		</div>
		</section>
		<p style="text-align: right; padding-right: 40px; font-size: 14px; background-color: white;
border-radius: 5px;">{{ post.date }}</p>



{% endfor %}

</div>

{% endblock content %}
</body>

metacats/blog/templates/blog/blog_single.html
{% extends 'maincat/base.html' %}
{% load static %}

<body>
{% block content %}

<div class="container4" style="margin: 100px; margin-top: 180px; ">
	<h1 class="intro__title">Last updates:</h1>

		<section class="section--gray" style="background-color: white;
border-radius: 5px;">
		<div class="container__post">
			<h3>{{ post.title }}</h3>
			<p>{{ post.anons }}</p>
			<p>{{ post.full_text }}</p>
		</div>
		</section>
		<p style="text-align: right; padding-right: 40px; font-size: 14px; background-color: white;
border-radius: 5px;">{{ post.date }}</p>
	<p>Comments:</p>

<h4> {% for comm in comment%}</h4>
	<a >{{comm.user}}</a>
	<p style="max-width: 600px; border-style: solid; border-width: 1px; border-radius: 10px; display: grid;">{{comm.text}}</p>
{% endfor%}

	<form method="post" style="display: grid;">
			{% csrf_token %}
            {{ form }}
            <p><button class="btn1" type="submit" style="margin-top: 20px;"> Add comment </button></p>
        </form>

</div>

{% endblock content %}
</body>